import Head from "next/head";

import { Divider, Form, Input, Select } from "antd";
import { useState } from "react";
import { useForm } from "antd/es/form/Form";



export default function Home() {
  const [form] = useForm()
  const [state,setState] = useState<{
    hex:string | null;
    jorm:string | null;
  }>({
    hex:null,jorm:null
  })
  const [preview,setPreview] = useState<string>('')
  const createNote= ()=>{
    const fields = form.getFieldsValue()
    return `\`\`\`1 .  Time : ${fields.time}
2 .  Steam Hex afard : ${state.hex}
3 . Punishments : ${state.jorm}
4 . Judge : ${fields.judge}
5 . Steam hex shaki (id discordfard  ): ${fields.shaki}
 Nahve daryaft shekayat ( report , ticket , ....  )  : ${fields.rah}\`\`\``
  }
   const handleFinish = ()=>{
    navigator.clipboard.writeText(createNote())
    form.resetFields()
    setState({hex:null,jorm:null})
   }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <button onClick={()=>navigator.clipboard.readText().then(r=> 
      setState({hex:r.split(' ')[2] ,jorm:r.split(':')[2]})
    )}>{state.hex?.includes('steam')?'Set shod':'Click me'}</button>
        <Divider/>

          {state.hex}     -    {state.jorm}
        <Divider/>

        <Form onFinish={()=>handleFinish()} layout="vertical" form={form}>
          <Form.Item label='shaki' name='shaki'>
            <Input />
          </Form.Item>
          <Form.Item label='time' name='time'>
            <Input />
          </Form.Item>
          <Form.Item label='judge' name='judge'>
            <Input />
          </Form.Item>
          <Form.Item initialValue='Temp' label='nahve ersal' name='rah'>
            <Select defaultValue='Temp' options={[{title:'Temp',value:'Temp'},{title:'Report',value:'Report'},{title:'Ticket',value:'Ticket'}]} />
          </Form.Item>
          <button type="submit">get note</button>
        </Form>
        <Divider/>
        <button onClick={()=>setPreview(createNote)}>preview</button>
        <button onClick={()=>setPreview('')}>hide preview</button>
        <Divider/>
        {preview !== '' && preview}
      </main>
    </>
  );
}
